const text=[
    'Another option you have is choosing the number of syllables in the words you speak. You probably have never considered this option before, but you have it every time you open your mouth and speak. You make so many choices like this that you never even think about, but you have the choice with each one. What are you going to do with this knowledge?',
    'Matt told her to reach for the stars, but Veronica thought it was the most ridiculous advice shed ever received. Sure, it had been well-meaning when he said it, but she didnt understand why anyone would want to suggest something that would literally kill you if you actually managed to achieve it.',
    'What was beyond the bend in the stream was unknown. Both were curious, but only one was brave enough to want to explore. That was the problem. There was always one that let fear rule her life.',
    'There was a reason for her shyness. Everyone assumed it had always been there but she knew better. She knew the exact moment that the shyness began. It had been that fateful moment at the lake. There are just some events that do that to you.',
    'There wasnt a whole lot more that could be done. It had become a wait-and-see situation with the final results no longer in her control. That didnt stop her from trying to control the situation. She demanded that things be done as she desperately tried to control what couldn',
    'He had done everything right. There had been no mistakes throughout the entire process. It had been perfection and he knew it without a doubt, but the results still stared back at him with the fact that he had lost.',
    'She tried to explain that love wasnt like pie. There wasnt a set number of slices to be given out. There wasnt less to be given to one person if you wanted to give more to another. That after a set amount was given out it would all disappear. She tried to explain this, but it fell on deaf ears.',
    'It wasnt that he hated her. It was simply that he didnt like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didnt, and no matter how he tried to explain to her she refused to listen or to understand.',
    'I recently discovered I could make fudge with just chocolate chips, sweetened condensed milk, vanilla extract, and a thick pot on slow heat. I tried it with dark chocolate chunks and I tried it with semi-sweet chocolate chips. Its better with both kinds. It comes out pretty bad with just the dark chocolate.',
    'A long black shadow slid across the pavement near their feet and the five Venusians, very much startled, looked overhead. They were barely in time to see the huge gray form of the carnivore before it vanished behind a sign atop a nearby building which bore the mystifying information "Pepsi-Cola."',
    'It wasnt that he hated her. It was simply that he didnt like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didnt, and no matter how he tried to explain to her she refused to listen or to understand',
    'Welcome to my world. You will be greeted by the unexpected here and your mind will be challenged and expanded in ways that you never thought possible. That is if you are able to survive...',
    'One can cook on and with an open fire. These are some of the ways to cook with fire outside. Cooking meat using a spit is a great way to evenly cook meat. In order to keep meat from burning, its best to slowly rotate it. Hot stones can be used to toast bread. Coals are hot and can bring things to a boil quickly.',
    'The bowl was filled with fruit. It seemed to be an overabundance of strawberries, but it also included blueberries, raspberries, grapes, and banana slices. This was the meal Sarah had every morning to start her day since she could remember. ',
    'It was their first date and she had been looking forward to it the entire week. She had her eyes on him for months, and it had taken a convoluted scheme with several friends to make it happen, but hed finally taken the hint and asked her out',
]
export default text;